-- Written by: Cherry 29/06/2015
-- Checked by: Angela 30/06/2015

DROP TABLE IF EXISTS Exams;
DROP TABLE IF EXISTS Questions;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Teachers;
DROP TABLE IF EXISTS ExamRecords;
DROP TABLE IF EXISTS QuesRecords;

CREATE TABLE Questions(
	quesID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ques VARCHAR(1000) NOT NULL,
	answer CHAR NOT NULL,
	opA VARCHAR(1000) NOT NULL,
	opB VARCHAR(1000) NOT NULL,
	opC VARCHAR(1000) NOT NULL,
	opD VARCHAR(1000) NOT NULL,
	feedA VARCHAR(1000) NOT NULL,
	feedB VARCHAR(1000) NOT NULL,
	feedC VARCHAR(1000) NOT NULL,
	feedD VARCHAR(1000) NOT NULL);

CREATE TABLE Exams(
	examID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	examTitle VARCHAR(1000) NOT NULL,
	examPW VARCHAR(6) NOT NULL,
	quesID INT NOT NULL,
	CONSTRAINT QuesExamFK FOREIGN KEY (quesID) REFERENCES Questions (quesID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Students(
	stuID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	stuUN VARCHAR(15) NOT NULL,
	stuPW VARCHAR(15) NOT NULL);

CREATE TABLE Teachers(
	teaID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	teaUN VARCHAR(15) NOT NULL,
	teaPW VARCHAR(15) NOT NULL);

CREATE TABLE ExamRecords(
	examID INT NOT NULL,
	teaID INT NOT NULL,
	CONSTRAINT RecordExamFK FOREIGN KEY (examID) REFERENCES Exams (examID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT RecordTeaFK FOREIGN KEY (teaID) REFERENCES Teachers (teaID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE QuesRecords(
	quesID INT NOT NULL,
	stuID INT NOT NULL,
	stuAns CHAR,
	CONSTRAINT RecordQuesFK FOREIGN KEY (quesID) REFERENCES Questions (quesID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT RecordStuFK FOREIGN KEY (stuID) REFERENCES Students (stuID) ON DELETE CASCADE ON UPDATE CASCADE);
