-- Written by: Cherry 29/06/2015
-- Checked by: Angela 30/06/2015

DROP TABLE IF EXISTS Exams;
DROP TABLE IF EXISTS Questions;

CREATE TABLE Questions(
	quesID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ques VARCHAR(1000) NOT NULL,
	answer CHAR NOT NULL,
	opA VARCHAR(1000) NOT NULL,
	opB VARCHAR(1000) NOT NULL,
	opC VARCHAR(1000) NOT NULL,
	opD VARCHAR(1000) NOT NULL,
	feedA VARCHAR(1000) NOT NULL,
	feedB VARCHAR(1000) NOT NULL,
	feedC VARCHAR(1000) NOT NULL,
	feedD VARCHAR(1000) NOT NULL);

CREATE TABLE Exams(
	examID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	examTitle VARCHAR(1000) NOT NULL,
	quesID INT NOT NULL,
	CONSTRAINT QuesExamFK FOREIGN KEY (quesID) REFERENCES Questions (quesID) ON DELETE CASCADE ON UPDATE CASCADE);
